### ISSUE TITLE
Which OS & docker version used for this tutorial

### ISSUE THREAD

**Issue by tinydjp** [51nodes/polkadot-local-rococo#1]
Hi，I'm stuck with the parachain register and found your tutorial. It's the simplest version I got, but when I ran docker compose in my local machine, I got errors like
`relaychain-bob_1    | 2021-05-09 00:35:48  🙌 Starting consensus session on top of parent 0xb454fba16ecadf6fa98e64a25a96bc6a13bf39b9e25b6f6673201bfe4d50f1d6    
relaychain-bob_1    | 2021-05-09 00:35:48  panicked at 'Bitfields and heads must be included every block', /home/ricardo/.dev/polkadot/runtime/parachains/src/inclusion_inherent.rs:83:17    
relaychain-bob_1    | 2021-05-09 00:35:48  Proposing failed: ClientImport("Blockchain(RuntimeApiError(Application(Execution(Wasmi(Trap(Trap { kind: Unreachable }))))))")  `
May I know is there any requirements for docker or OS version?

**Comment by tinydjp** [comment]
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:47:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:45:28 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by tinydjp** [comment]
OS: Ubuntu 20.04 X86 64

**Comment by marc0olo** [comment]
Hi @tinydjp,

there shouldn't be any limitations regarding the OS and Docker version as far as I know. I am facing the same issue right now when launching the docker-compose and I am quite sure that error didn't occur in the past.

So it seems like Parity updates the Rococo image from time to time and probably requires another configuration now. I am sorry for that! Don't have the time actually to investigate further.

https://hub.docker.com/layers/parity/rococo/rococo-v1/images/sha256-0c5085f4e0cc309798bf4dcc893f39814bb8d5e883587afdf02fed525b3bba57?context=explore was updated 4 days ago and I tested the setup you are trying to get working 3 months ago. So there might have been a lot of changes. Unfortunately I didn't use a specific hash of the image so you automatically pulled the latest version of it.

**Comment by tinydjp** [comment]
> Hi @tinydjp,
> 
> there shouldn't be any limitations regarding the OS and Docker version as far as I know. I am facing the same issue right now when launching the docker-compose and I am quite sure that error didn't occur in the past.
> 
> So it seems like Parity updates the Rococo image from time to time and probably requires another configuration now. I am sorry for that! Don't have the time actually to investigate further.
> 
> https://hub.docker.com/layers/parity/rococo/rococo-v1/images/sha256-0c5085f4e0cc309798bf4dcc893f39814bb8d5e883587afdf02fed525b3bba57?context=explore was updated 4 days ago and I tested the setup you are trying to get working 3 months ago. So there might have been a lot of changes. Unfortunately I didn't use a specific hash of the image so you automatically pulled the latest version of it.

Thanks for your response, I've figured it out. Just like you told, it's an version mismatching problem, the json files are out of date. I downloaded latest version from https://substrate.dev/cumulus-workshop/#/en/1-prep/2-chain-spec , it worked.
